services:
  config-server:
    image: ghcr.io/internal-job-portal/config-server:latest
    ports:
      - "8888:8888"
    environment:
      - TZ=${TZ}
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
      - CONFIG_PROFILE=${CONFIG_PROFILE}
      - CONFIG_GIT_URI=${CONFIG_GIT_URI}
    networks:
      - ijp-network
    hostname: config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - ijp-network

  kafka:
    image: docker.io/confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ijp-network

  api-gateway:
    image: ghcr.io/internal-job-portal/api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      - TZ=${TZ}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - LOGIN_SERVICE_URI=${LOGIN_SERVICE_URI}
      - HR_SERVICE_URI=${HR_SERVICE_URI}
      - JOB_SERVICE_URI=${JOB_SERVICE_URI}
      - CANDIDATE_SERVICE_URI=${CANDIDATE_SERVICE_URI}
      - EMPLOYEE_SERVICE_URI=${EMPLOYEE_SERVICE_URI}
    depends_on:
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy
    networks:
      - ijp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  login-service:
    image: ghcr.io/internal-job-portal/login-service:latest
    ports:
      - "8081:8081"
    environment:
      - TZ=${TZ}
      - LOGIN_SERVICE_PORT=${LOGIN_SERVICE_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - HR_SERVICE_URI=${HR_SERVICE_URI}
      - EMPLOYEE_SERVICE_URI=${EMPLOYEE_SERVICE_URI}
    networks:
      - ijp-network
    depends_on:
      config-server:
        condition: service_healthy

  hr-service:
    image: ghcr.io/internal-job-portal/hr-service:latest
    ports:
      - "8082:8082"
    environment:
      - TZ=${TZ}
      - PROFILE=${PROFILE}
      - HR_SERVICE_PORT=${HR_SERVICE_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - HR_DB_NAME=${HR_DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - H2_USERNAME=${H2_USERNAME}
      - H2_PASSWORD=${H2_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    networks:
      - ijp-network
    depends_on:
      config-server:
        condition: service_healthy
      db:
        condition: service_healthy
      kafka:
        condition: service_started

  job-service:
    image: ghcr.io/internal-job-portal/job-service:latest
    ports:
      - "8083:8083"
    environment:
      - TZ=${TZ}
      - PROFILE=${PROFILE}
      - JOB_SERVICE_PORT=${JOB_SERVICE_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - JOB_DB_NAME=${JOB_DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - H2_USERNAME=${H2_USERNAME}
      - H2_PASSWORD=${H2_PASSWORD}
      - CANDIDATE_SERVICE_URI=${CANDIDATE_SERVICE_URI}
    networks:
      - ijp-network
    depends_on:
      config-server:
        condition: service_healthy
      db:
        condition: service_healthy

  candidate-service:
    image: ghcr.io/internal-job-portal/candidate-service:latest
    ports:
      - "8084:8084"
    environment:
      - TZ=${TZ}
      - PROFILE=${PROFILE}
      - CANDIDATE_SERVICE_PORT=${CANDIDATE_SERVICE_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - CANDIDATE_DB_NAME=${CANDIDATE_DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - H2_USERNAME=${H2_USERNAME}
      - H2_PASSWORD=${H2_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    networks:
      - ijp-network
    depends_on:
      config-server:
        condition: service_healthy
      db:
        condition: service_healthy
      kafka:
        condition: service_started

  employee-service:
    image: ghcr.io/internal-job-portal/employee-service:latest
    ports:
      - "8085:8085"
    environment:
      - TZ=${TZ}
      - PROFILE=${PROFILE}
      - EMPLOYEE_SERVICE_PORT=${EMPLOYEE_SERVICE_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EMPLOYEE_DB_NAME=${EMPLOYEE_DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - H2_USERNAME=${H2_USERNAME}
      - H2_PASSWORD=${H2_PASSWORD}
    networks:
      - ijp-network
    depends_on:
      config-server:
        condition: service_healthy
      db:
        condition: service_healthy

  frontend:
    image: ghcr.io/internal-job-portal/frontend:latest
    ports:
      - "80:80"
    environment:
      - TZ=${TZ}
    networks:
      - ijp-network
    depends_on:
      api-gateway:
        condition: service_healthy

  db:
    image: docker.io/library/postgres:17
    environment:
      - TZ=Asia/Kolkata
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
      - PGPORT=5432
    ports:
      - "5432:5432"
    volumes:
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ijp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  ijp-network:
    name: ijp-network
