apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: {{ .Values.configServer.replicaCount }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: "{{ .Values.images.registry }}/{{ .Values.images.configServer.repository }}:{{ .Values.images.configServer.tag }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: {{ .Values.configServer.port }}
        envFrom:
        - configMapRef:
            name: ijp-config
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.configServer.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.configServer.port }}
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
  - port: {{ .Values.configServer.port }}
    targetPort: {{ .Values.configServer.port }}
  type: ClusterIP
