apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ijp-ingress
spec:
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.frontend.port }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: {{ .Values.apiGateway.port }}
