apiVersion: v1
kind: Secret
metadata:
  name: ijp-secrets
type: Opaque
stringData:
  # Database Credentials
  POSTGRES_USERNAME: {{ .Values.database.username }}
  POSTGRES_PASSWORD: {{ .Values.database.password }}
  H2_USERNAME: {{ .Values.database.h2Username }}
  H2_PASSWORD: {{ .Values.database.h2Password }}
  
  # JWT Secret
  JWT_SECRET: {{ .Values.jwt.secret }}
