# Global configuration
global:
  timezone: "Asia/Kolkata"
  domain: "ijp.example.com"
  storageClass: "standard"
  
# Common environment variables
env:
  profile: "prod"

# Database configuration
database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "root"
  h2Username: "sa"
  h2Password: "password"
  multipleDatabases: "hr_db,job_db,candidate_db,employee_db"
  storageSize: "2Gi"

# Config server
configServer:
  port: 8888
  profile: "git"
  gitUri: "https://github.com/internal-job-portal/config.git"
  replicaCount: 1

# JWT settings
jwt:
  secret: "QYnPfUxXgHQ5FyWWPLss1rlRfgSsd6dZQDwWE="
  expiration: "86400000"
  
# API Gateway
apiGateway:
  port: 8080
  replicaCount: 1

# Login Service
loginService:
  port: 8081
  replicaCount: 1

# HR Service
hrService:
  port: 8082
  dbName: "hr_db"
  replicaCount: 1

# Job Service
jobService:
  port: 8083
  dbName: "job_db"
  replicaCount: 1

# Candidate Service
candidateService:
  port: 8084
  dbName: "candidate_db"
  replicaCount: 1

# Employee Service
employeeService:
  port: 8085
  dbName: "employee_db"
  replicaCount: 1

# Frontend
frontend:
  port: 80
  replicaCount: 1

# Service URLs (internal)
serviceUrls:
  configServer: "http://config-server:8888"
  loginService: "http://login-service:8081"
  hrService: "http://hr-service:8082"
  jobService: "http://job-service:8083"
  candidateService: "http://candidate-service:8084"
  employeeService: "http://employee-service:8085"

# Image configuration
images:
  registry: "ghcr.io/internal-job-portal"
  pullPolicy: Always
  
  configServer: 
    repository: config-server
    tag: latest
  apiGateway:
    repository: api-gateway
    tag: latest
  loginService:
    repository: login-service
    tag: latest
  hrService:
    repository: hr-service
    tag: latest
  jobService:
    repository: job-service
    tag: latest
  candidateService:
    repository: candidate-service
    tag: latest
  employeeService:
    repository: employee-service
    tag: latest
  frontend:
    repository: frontend
    tag: latest
  postgres:
    repository: postgres
    tag: "17"

kafka:
  bootstrapServers: "kafka-kafka-bootstrap.kafka.svc:9092"
