apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
 name: controller
 namespace: kafka
 labels:
   strimzi.io/cluster: kafka
spec:
 replicas: 1
 roles:
   - controller
 storage:
   type: jbod
   volumes:
     - id: 0
       type: persistent-claim
       size: 5Gi
       deleteClaim: true